const UserList=[
    {
        id:1,
        name:"John",
        username:"john",
        age:20,
        nationality:"Canada",
    },
    {
        id:2,
        name:"Doe",
        username:"doe",
        age:22,
        nationality:"America",
    },
    {
        id:4,
        name:"Riya",
        username:"riya",
        age:22,
        nationality:"India",
    },
    {
        id:5,
        name:"Tejjus",
        username:"tejjus",
        age:25,
        nationality:"India",
    },
    {
        id:6,
        name:"Shlok",
        username:"shlok",
        age:22,
        nationality:"India",
    },
]

module.exports ={UserList}